[package]
name = "vrctv-common"
version = "0.2.0"
edition = "2024"

[dependencies]
ts-rs = { version = "11.0.1", features = ["serde-json-impl"] }
serde = { workspace = true }
serde_json = { workspace = true }
